### ISSUE TITLE
[UC] Split contracts

### ISSUE THREAD

**Issue by myronrotter** [cp-ss2019/decentralized-energy-trading#19]
Currently, the UC is seperated in Owned.sol, Mortal.sol and Utility.sol including IUtility.sol as interface.

Seperate Utility.sol such that there is one contract for renewable energy tracking and one for non-renewable energy tracking (both contracts implemented the same) as well as one contract for settlement (netting) calling both tracking contracts for netting algorithm.

**Comment by myronrotter** [comment]
I just tried to split Utility.sol into Households.sol, Energy.sol and Settlement.sol. In this case, there is an overhead of setter/getter function calls just to implement easy tracking. Furthermore, setter functions like setHousehold for setting energy consumption/production have to be restricted somehow. Any suggestions @minhi?

**Comment by minhi** [comment]
Having a generic structure to describe energy sounds like a good idea since we could use this for both clean and traditional energy. Currently, we're repeating ourselves, e.g., `decreaseRenewableEnergy`
`decreaseNonRenewableEnergy`, so.. yeah.

Having a sole file for settlement and for household management/tracking sounds like a great idea too.

**Comment by minhi** [comment]
Currently I'm thinking of using `onlyOwner` for something like `addHousehold`, while the owner of the UC is assumed to be an address of a multi signature contract owned by "trusted people".

**Comment by myronrotter** [comment]
PR #36 splits contracts. Probably need to refactor contract names as @minhi suggested.
